sonar.projectName=Domesticas App
sonar.projectVersion=0.0.1-SNAPSHOT
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.test.exclusions=src/test/java/**
sonar.sourceEncoding=UTF-8
sonar.language=java
sonar.java.source=21
sonar.java.target=21

# Configuración de cobertura con JaCoCo
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusiones de código productivo
sonar.exclusions=**/*Application.java,**/config/**,**/dto/**,**/model/**

# Quality Gates
sonar.qualitygate.wait=true

# Detección de bugs
sonar.java.checkstyle.reportPaths=target/checkstyle-result.xml

# Duplicación de código
sonar.cpd.exclusions=**/*Test*.java
