spring.application.name=domesticas
# Conexión a PostgreSQL en Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/domesticas_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate — validate verifica que las entidades coincidan con las tablas sin modificar nada
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuración JWT
app.jwt.secret=clave-super-secreta-larga-para-firmar-tokens-domesticas-2024
app.jwt.expiration=86400000
spring.jpa.open-in-view=false
springdoc.use-hateoas=false
spring.autoconfigure.exclude=org.springdoc.core.configuration.SpringDocHateoasConfiguration