spring.application.name=domesticas
# Le dice a Spring dónde está tu base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/domesticas_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate — validate verifica que el esquema coincida con tus entidades
# sin modificar nada. Ideal cuando ya tienes la BD montada como es tu caso.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect